### PR TITLE
Add XavierWatson page

### PR DESCRIPTION
**Pull request by XavierWatson**
Added Username view for Xavier Watson, Added Username controller meth…od, Added Route for username

### CODE REVIEW

**Review by prav-raj — DISMISSED** [review]
All good

**Review by christophervalle85 — DISMISSED** [review]
nice

**Comment by not-Cha0s** [comment]
looks good

**Review by prav-raj — APPROVED** [review]
good

**Review by kbridson — APPROVED** [review]
Looks good

**Pull request merged**
